version: '3'
services:
  inventoryManager_db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: Asia/Seoul